name: Compile and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build library
        run: make

      - name: Test library
        run: make test

      - name: Build examples (C)
        run: make getting_started filecopy freertos

      - name: Build examples (C++)
        run: make getting_started_cxx filecopy_cxx freertos_cxx
